import React, { useEffect, useMemo, useState } from 'react';
import { ClipboardList, FileDown, History, Printer, Save, RefreshCw } from 'lucide-react';
import api, { formatApiError } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { toast } from '../hooks/use-toast';

const num = (v) => Number(v || 0).toLocaleString('en-US', { maximumFractionDigits: 2 });

export default function InventoryAudits() {
  const { user } = useAuth();
  const [products, setProducts] = useState([]); const [rows, setRows] = useState([]); const [audits, setAudits] = useState([]);
  const [branch, setBranch] = useState('ميني ماركت الفنية'); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const [p, a] = await Promise.all([api.get('/products', { params: { limit: 1000 } }), api.get('/admin/inventory-audits')]); setProducts(p.data); setRows(p.data.map(x => ({ product_id: x.id, actual_quantity: Number(x.current_stock || 0) }))); setAudits(a.data); } catch (e) { toast({ title: 'تعذر تحميل الجرد', description: formatApiError(e), variant: 'destructive' }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const setActual = (id, value) => setRows(prev => prev.map(x => x.product_id === id ? { ...x, actual_quantity: value === '' ? '' : Math.max(0, Number(value)) } : x));
  const save = async () => { setSaving(true); try { const r = await api.post('/admin/inventory-audits', { branch, notes, items: rows.map(x => ({ product_id: x.product_id, actual_quantity: Number(x.actual_quantity || 0) })) }); toast({ title: 'تم حفظ الجرد', description: r.data.audit_no }); await load(); } catch (e) { toast({ title: 'فشل حفظ الجرد', description: formatApiError(e), variant: 'destructive' }); } finally { setSaving(false); } };
  const pdf = async (url, name, print = false) => { const popup = print ? window.open('', '_blank') : null; try { const r = await api.get(url, { responseType: 'blob' }); const href = URL.createObjectURL(r.data); if (popup) { popup.location.href = href; } else { const a = document.createElement('a'); a.href = href; a.download = name; document.body.appendChild(a); a.click(); a.remove(); } setTimeout(() => URL.revokeObjectURL(href), 60000); } catch (e) { if (popup) popup.close(); toast({ title: 'فشل إنشاء PDF', description: formatApiError(e), variant: 'destructive' }); } };
  const actualTotal = useMemo(() => rows.reduce((s, r) => s + Number(r.actual_quantity || 0), 0), [rows]);
  if (!['admin', 'manager'].includes(user?.role)) return <div className="p-8 text-center text-slate-600">لا تملك صلاحية الوصول إلى الجرد.</div>;
  return <div className="p-6 space-y-6" dir="rtl">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2"><ClipboardList className="text-amber-500" /> جرد المخزون</h1><p className="text-sm text-slate-500 mt-1">تسجيل الكمية الفعلية دون تعديل كمية النظام.</p></div><div className="flex gap-2"><button onClick={() => pdf('/admin/inventory-audits/current/pdf', 'inventory-audit-current.pdf', true)} className="px-4 py-2 rounded-lg bg-slate-800 text-white flex gap-2 items-center"><Printer size={16}/> طباعة جرد مخزون حالي</button><button onClick={load} className="px-3 py-2 rounded-lg border flex gap-2 items-center"><RefreshCw size={16}/> تحديث</button></div></div>
    <div className="bg-white border rounded-xl p-4 shadow-sm"><div className="flex flex-wrap gap-3 mb-4"><input value={branch} onChange={e => setBranch(e.target.value)} className="border rounded-lg px-3 py-2" placeholder="المستودع / الفرع"/><input value={notes} onChange={e => setNotes(e.target.value)} className="border rounded-lg px-3 py-2 flex-1" placeholder="ملاحظات الجرد"/><button disabled={saving || loading} onClick={save} className="px-4 py-2 rounded-lg bg-amber-500 text-white disabled:opacity-50 flex gap-2 items-center"><Save size={16}/> {saving ? 'جارٍ الحفظ...' : 'حفظ الجرد'}</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-900 text-white"><th className="p-3">م</th><th className="p-3">الباركود (كود المنتج)</th><th className="p-3">اسم المنتج</th><th className="p-3">الوحدة</th><th className="p-3">الكمية الفعلية</th><th className="p-3">كمية النظام</th><th className="p-3">تكلفة الوحدة</th></tr></thead><tbody>{products.map((p, i) => <tr key={p.id} className="border-b hover:bg-slate-50"><td className="p-3">{i + 1}</td><td className="p-3 font-mono">{p.barcodes?.[0] || '—'}</td><td className="p-3 font-medium">{p.name}</td><td className="p-3">{p.unit || 'piece'}</td><td className="p-3"><input type="number" min="0" value={rows.find(x => x.product_id === p.id)?.actual_quantity ?? ''} onChange={e => setActual(p.id, e.target.value)} className="w-28 border rounded px-2 py-1" /></td><td className="p-3">{num(p.current_stock)}</td><td className="p-3">{num(p.cost_price)}</td></tr>)}</tbody></table></div><div className="mt-4 text-sm text-slate-600">إجمالي الكمية الفعلية: <b>{num(actualTotal)}</b> — عدد الأصناف: <b>{products.length}</b></div></div>
    <div className="bg-white border rounded-xl p-4 shadow-sm"><h2 className="font-bold flex items-center gap-2 mb-3"><History size={18}/> سجل الجرد</h2><div className="space-y-2">{audits.length ? audits.map(a => <div key={a.id} className="flex flex-wrap justify-between items-center border rounded-lg p-3"><span><b>{a.audit_no}</b> — {a.actor_name} — {new Date(a.created_at).toLocaleString('ar-EG')}</span><button onClick={() => pdf(`/admin/inventory-audits/${a.id}/pdf`, `${a.audit_no}.pdf`)} className="text-amber-700 flex gap-1 items-center"><FileDown size={16}/> PDF</button></div>) : <p className="text-slate-500">لا توجد سجلات جرد بعد.</p>}</div></div>
  </div>;
}
